CONTAINER SyphonPlugin
{
	NAME SyphonPlugin;
	INCLUDE VPbase;

	GROUP ID_VIDEOPOSTPROPERTIES
	{
		DEFAULT 1;

		BOOL VP_SYPHON_ENABLED	{ }
		LONG VP_SYPHON_MODE		{ CYCLE { VP_SYPHON_MODE_REALTIME; VP_SYPHON_MODE_FRAME; }; }

		GROUP
		{
			STATICTEXT { NAME VP_SYPHON_WARNING1;  }
			STATICTEXT { NAME VP_SYPHON_WARNING2;  }
		}
	}
}

